"""Initial MVP schema

Revision ID: 6f0e6720530e
Revises: 
Create Date: 2026-08-27 22:56:28.979428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f0e6720530e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # required for gen_random_uuid() used as the default for every table's id column
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('points >= 0', name='ck_badges_points'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('class_level', sa.SmallInteger(), server_default=sa.text('10'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('class_level = 10', name='ck_subjects_class_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'class_level', name='uq_subjects_name_class')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('student', 'teacher')", name='ck_users_role'),
    sa.CheckConstraint('length(btrim(full_name)) > 0', name='ck_users_full_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chapters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order > 0', name='ck_chapters_display_order'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'display_order', name='uq_chapters_subject_order'),
    sa.UniqueConstraint('subject_id', 'name', name='uq_chapters_subject_name')
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('class_level', sa.SmallInteger(), server_default=sa.text('10'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('class_level = 10', name='ck_student_profiles_class_level'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('teacher_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('curriculum_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_uri', sa.String(length=2048), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_hash ~ '^[0-9a-fA-F]{64}$'", name='ck_curriculum_documents_hash'),
    sa.CheckConstraint("document_type IN ('syllabus', 'reference', 'sample_paper')", name='ck_curriculum_documents_type'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_curriculum_documents_content_hash'),
    sa.UniqueConstraint('source_uri', name='uq_curriculum_documents_source_uri')
    )
    op.create_table('student_badges',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('student_id', 'badge_id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order > 0', name='ck_topics_display_order'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'display_order', name='uq_topics_chapter_order'),
    sa.UniqueConstraint('chapter_id', 'name', name='uq_topics_chapter_name')
    )
    op.create_table('exams',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('question_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_count', sa.SmallInteger(), nullable=False),
    sa.Column('time_limit_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='ck_exams_difficulty'),
    sa.CheckConstraint("jsonb_typeof(question_types) = 'array' AND jsonb_array_length(question_types) > 0", name='ck_exams_question_types'),
    sa.CheckConstraint('question_count BETWEEN 1 AND 50', name='ck_exams_question_count'),
    sa.CheckConstraint('time_limit_minutes BETWEEN 1 AND 180', name='ck_exams_time_limit'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('question_count', sa.SmallInteger(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('question_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'recommended'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='ck_recommendations_difficulty'),
    sa.CheckConstraint("status IN ('recommended', 'accepted', 'completed', 'dismissed')", name='ck_recommendations_status'),
    sa.CheckConstraint('question_count BETWEEN 1 AND 50', name='ck_recommendations_count'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('class_level', sa.SmallInteger(), server_default=sa.text('10'), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('bloom_level', sa.String(length=20), nullable=True),
    sa.Column('marks', sa.SmallInteger(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('learning_objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'generated'"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(question_type = 'mcq' AND jsonb_typeof(options) = 'array' AND jsonb_array_length(options) = 4) OR (question_type <> 'mcq' AND options IS NULL)", name='ck_questions_options_shape'),
    sa.CheckConstraint("bloom_level IS NULL OR bloom_level IN ('remember', 'understand', 'apply', 'analyze')", name='ck_questions_bloom'),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='ck_questions_difficulty'),
    sa.CheckConstraint("question_type IN ('mcq', 'numerical', 'short_answer', 'long_answer', 'competency')", name='ck_questions_type'),
    sa.CheckConstraint("status IN ('generated', 'validated', 'rejected', 'approved')", name='ck_questions_status'),
    sa.CheckConstraint('class_level = 10', name='ck_questions_class_level'),
    sa.CheckConstraint('marks > 0', name='ck_questions_marks'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_references',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.String(length=200), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_number IS NOT NULL OR chunk_id IS NOT NULL', name='ck_source_references_locator'),
    sa.CheckConstraint('page_number IS NULL OR page_number > 0', name='ck_source_references_page'),
    sa.ForeignKeyConstraint(['document_id'], ['curriculum_documents.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', 'chunk_id', name='uq_source_references_location')
    )
    op.create_table('topic_performance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('correct_answers', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('score_earned', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('score_possible', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('score_percentage', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'needs_practice'"), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('strong', 'good', 'needs_practice')", name='ck_topic_performance_status'),
    sa.CheckConstraint('attempts >= 0 AND correct_answers >= 0', name='ck_topic_performance_counts'),
    sa.CheckConstraint('score_earned >= 0 AND score_possible >= 0', name='ck_topic_performance_scores'),
    sa.CheckConstraint('score_percentage BETWEEN 0 AND 100', name='ck_topic_performance_percentage'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'topic_id', name='uq_topic_performance_student_topic')
    )
    op.create_table('exam_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'assigned'"), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('assigned', 'started', 'completed', 'expired')", name='ck_exam_assignments_status'),
    sa.ForeignKeyConstraint(['assigned_by'], ['teacher_profiles.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_exam_assignments_exam_student')
    )
    op.create_table('exam_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence_no > 0', name='ck_exam_questions_sequence'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'question_id', name='uq_exam_questions_question'),
    sa.UniqueConstraint('exam_id', 'sequence_no', name='uq_exam_questions_sequence')
    )
    op.create_table('question_source_references',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('source_reference_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('relevance_score IS NULL OR relevance_score BETWEEN 0 AND 1', name='ck_qsr_relevance'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_references.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'source_reference_id')
    )
    op.create_table('question_validation_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('curriculum_relevance', sa.Boolean(), nullable=False),
    sa.Column('answer_correctness', sa.Boolean(), nullable=False),
    sa.Column('difficulty_match', sa.Boolean(), nullable=False),
    sa.Column('type_match', sa.Boolean(), nullable=False),
    sa.Column('duplicate_check', sa.Boolean(), nullable=False),
    sa.Column('learning_objective_alignment', sa.Boolean(), nullable=False),
    sa.Column('failure_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'validated' AND curriculum_relevance AND answer_correctness AND difficulty_match AND type_match AND duplicate_check AND learning_objective_alignment) OR (status = 'rejected' AND NOT (curriculum_relevance AND answer_correctness AND difficulty_match AND type_match AND duplicate_check AND learning_objective_alignment))", name='ck_qvr_status_checks'),
    sa.CheckConstraint("jsonb_typeof(failure_reasons) = 'array'", name='ck_qvr_failure_reasons'),
    sa.CheckConstraint("status IN ('validated', 'rejected')", name='ck_qvr_status'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_score', sa.SmallInteger(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'in_progress' AND submitted_at IS NULL AND score IS NULL AND percentage IS NULL) OR (status = 'submitted' AND submitted_at IS NOT NULL AND score IS NOT NULL AND percentage IS NOT NULL)", name='ck_attempts_result_state'),
    sa.CheckConstraint("status IN ('in_progress', 'submitted')", name='ck_attempts_status'),
    sa.CheckConstraint('max_score > 0', name='ck_attempts_max_score'),
    sa.CheckConstraint('percentage IS NULL OR percentage BETWEEN 0 AND 100', name='ck_attempts_percentage'),
    sa.CheckConstraint('score IS NULL OR score >= 0', name='ck_attempts_score'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_student_attempts_active', 'student_attempts', ['exam_id', 'student_id'], unique=True, postgresql_where=sa.text("status = 'in_progress'"))
    op.create_table('student_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('submitted_answer', sa.String(length=4000), nullable=True),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('score_awarded', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('max_score', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_score > 0', name='ck_student_answers_max_score'),
    sa.CheckConstraint('score_awarded >= 0', name='ck_student_answers_score'),
    sa.CheckConstraint('submitted_answer IS NULL OR length(btrim(submitted_answer)) > 0', name='ck_student_answers_answer'),
    sa.ForeignKeyConstraint(['attempt_id'], ['student_attempts.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_student_answers_attempt_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_answers')
    op.drop_index('uq_student_attempts_active', table_name='student_attempts', postgresql_where=sa.text("status = 'in_progress'"))
    op.drop_table('student_attempts')
    op.drop_table('question_validation_results')
    op.drop_table('question_source_references')
    op.drop_table('exam_questions')
    op.drop_table('exam_assignments')
    op.drop_table('topic_performance')
    op.drop_table('source_references')
    op.drop_table('questions')
    op.drop_table('practice_recommendations')
    op.drop_table('exams')
    op.drop_table('topics')
    op.drop_table('student_badges')
    op.drop_table('curriculum_documents')
    op.drop_table('teacher_profiles')
    op.drop_table('student_profiles')
    op.drop_table('chapters')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('badges')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
